layout_spectrum: 1
typography_spectrum: 0.9121864
color:
  saturation: 0.617002
  brandStrength: 0.7246763
  lightness: 0.1899642
  brandColors:
    - '#FFFFFF'
    - '#000000'
  rhythmicContrast: 0.5009897
name: Xinc
